# Generated by Django 6.1.1 on 2026-10-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_servicio_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
